# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hamlet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hamlet
  pod 'ACFloatingTextfield-Swift', '~> 1.8'
  pod 'Alamofire', '~> 5.2'
  pod 'Toast-Swift', '~> 5.0'
  pod 'MBProgressHUD', '~> 1.2'
  pod 'SDWebImage', '~> 5.9'
  pod 'IQKeyboardManager', '~> 6.5'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'


end
